CREATE TABLE endereco (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	cep VARCHAR(8) NOT NULL,
	logradouro VARCHAR(100) NOT NULL,
	bairro VARCHAR(50) NOT NULL,
	cidade VARCHAR(50) NOT NULL,
	uf VARCHAR(20) NOT NULL,
	complemento VARCHAR(120)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;		


CREATE TABLE cliente (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	codigo_endereco BIGINT(20) NOT NULL,
	FOREIGN KEY (codigo_endereco) REFERENCES endereco(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
